# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
import numpy as np

In [2]:
# Ejercicio 1
ej1 = np.zeros(12)
print(ej1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Ejercicio 2
# creo un array de ceros
ej2 = np.zeros(10)
# selecciono la posición 5 y le asigno el valor 10
ej2[5] = 10 #asumo que se refiere a posicion 5 y no quinta posición
print(ej2)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [4]:
# Ejercicio 3
ej3 = np.arange(10, 50)
print(ej3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
# Ejercicio 4
ej4 = np.arange(9).reshape(3, 3)
print(ej4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# Ejercicio 5
# creo un array de numeros aleatorios de longitud 100
np.random.seed(0)
ej5 = np.random.random(100)
# calculo su media
mej5 = np.mean(ej5)
print("Media =", mej5)
# calculo su varianza
vej5 = np.var(ej5)
print("Varianza =", vej5)

Media = 0.4727938395125177
Varianza = 0.08311781545439237


In [50]:
# Ejericio 6
# creo un arreglo cualquiera
ej6 = np.arange(0,20)
# calculo la suma de sus elementos
sumej6 = np.sum(ej6)
# calculo la cantidad total de elementos
nej6 = ej6.size
# calculo la media dividiendo la suma total por la cantidad de elementos
mej6 = sumej6/nej6
print("Media =", mej6)

Media = 9.5


In [39]:
# Ejercicio 7
# creo un arreglo cualquiera
ej7 = np.array([3, 5, 2, 8, 6, 4, 7])
# calculo la media del arreglo
mej7 = np.mean(ej7)
# restar la media a cada elemento del arreglo
desvej7 = ej7 - mej7
# elevar al cuadrado cada desviación
desvej7cuad = desvej7 ** 2
# calculo la media de las desviaciones al cuadrado
varej7 = np.mean(desvej7cuad)

print("Varianza =", varej7)


Varianza = 4.0


In [48]:
# Ejercicio 8
# creo un array cualquiera
ej8 = np.random.randn(5,3)
print("Array de 2d de numeros aleatorios: \n", ej8)

Array de 2d de numeros aleatorios: 
 [[ 0.70657317  0.01050002  1.78587049]
 [ 0.12691209  0.40198936  1.8831507 ]
 [-1.34775906 -1.270485    0.96939671]
 [-1.17312341  1.94362119 -0.41361898]
 [-0.74745481  1.92294203  1.48051479]]
15
